const booksData = [
  { 
    id: 1, 
    title: "The Great Gatsby", 
    author: "F. Scott Fitzgerald", 
    price: 12.99, 
    category: "Classic", 
    rating: 4.5, 
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=300&h=400&fit=crop&crop=center", 
    description: "A timeless classic about the American Dream in the Jazz Age.", 
    featured: true,
    color: "from-purple-400 to-pink-400"
  },
  { 
    id: 2, 
    title: "To Kill a Mockingbird", 
    author: "Harper Lee", 
    price: 14.99, 
    category: "Classic", 
    rating: 4.8, 
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=400&fit=crop&crop=center", 
    description: "A gripping tale of justice, morality, and childhood innocence.", 
    featured: true,
    color: "from-blue-400 to-cyan-400"
  },
  { 
    id: 3, 
    title: "1984", 
    author: "George Orwell", 
    price: 13.99, 
    category: "Dystopian", 
    rating: 4.7, 
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300&h=400&fit=crop&crop=center", 
    description: "A chilling vision of totalitarianism and surveillance society.", 
    featured: false,
    color: "from-red-400 to-orange-400"
  },
  { 
    id: 4, 
    title: "Pride and Prejudice", 
    author: "Jane Austen", 
    price: 11.99, 
    category: "Romance", 
    rating: 4.6, 
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=300&h=400&fit=crop&crop=center", 
    description: "A romantic masterpiece of wit, wisdom, and social commentary.", 
    featured: true,
    color: "from-pink-400 to-rose-400"
  },
  { 
    id: 5, 
    title: "The Hobbit", 
    author: "J.R.R. Tolkien", 
    price: 15.99, 
    category: "Fantasy", 
    rating: 4.9, 
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&h=400&fit=crop&crop=center", 
    description: "An epic adventure in Middle-earth that started it all.", 
    featured: true,
    color: "from-green-400 to-emerald-400"
  },
  { 
    id: 6, 
    title: "Dune", 
    author: "Frank Herbert", 
    price: 16.99, 
    category: "Sci-Fi", 
    rating: 4.8, 
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=400&fit=crop&crop=center", 
    description: "A science fiction masterpiece of politics and ecology.", 
    featured: false,
    color: "from-yellow-400 to-orange-400"
  },
  { 
    id: 7, 
    title: "The Catcher in the Rye", 
    author: "J.D. Salinger", 
    price: 12.99, 
    category: "Coming-of-Age", 
    rating: 4.3, 
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=300&h=400&fit=crop&crop=center", 
    description: "A coming-of-age story that defined a generation.", 
    featured: false,
    color: "from-indigo-400 to-purple-400"
  },
  { 
    id: 8, 
    title: "Harry Potter and the Philosopher's Stone", 
    author: "J.K. Rowling", 
    price: 14.99, 
    category: "Fantasy", 
    rating: 4.9, 
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop&crop=center", 
    description: "The magical world of wizards and witches begins here.", 
    featured: true,
    color: "from-yellow-400 to-amber-400"
  },
  { 
    id: 9, 
    title: "The Lord of the Rings", 
    author: "J.R.R. Tolkien", 
    price: 18.99, 
    category: "Fantasy", 
    rating: 4.9, 
    image: "https://images.unsplash.com/photo-1589998059171-988d887df646?w=300&h=400&fit=crop&crop=center", 
    description: "The epic fantasy trilogy that defined the genre.", 
    featured: true,
    color: "from-emerald-400 to-teal-400"
  },
  { 
    id: 10, 
    title: "The Chronicles of Narnia", 
    author: "C.S. Lewis", 
    price: 16.99, 
    category: "Fantasy", 
    rating: 4.7, 
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=400&fit=crop&crop=center", 
    description: "A magical journey through the wardrobe into Narnia.", 
    featured: false,
    color: "from-blue-400 to-indigo-400"
  },
  { 
    id: 11, 
    title: "The Alchemist", 
    author: "Paulo Coelho", 
    price: 13.99, 
    category: "Philosophy", 
    rating: 4.4, 
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&h=400&fit=crop&crop=center", 
    description: "A philosophical tale about following your dreams.", 
    featured: false,
    color: "from-amber-400 to-yellow-400"
  },
  { 
    id: 12, 
    title: "The Kite Runner", 
    author: "Khaled Hosseini", 
    price: 15.99, 
    category: "Drama", 
    rating: 4.6, 
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=300&h=400&fit=crop&crop=center", 
    description: "A powerful story of friendship, betrayal, and redemption.", 
    featured: false,
    color: "from-orange-400 to-red-400"
  },
  { 
    id: 13, 
    title: "The Book Thief", 
    author: "Markus Zusak", 
    price: 14.99, 
    category: "Historical Fiction", 
    rating: 4.7, 
    image: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=300&h=400&fit=crop&crop=center", 
    description: "A story of a young girl in Nazi Germany who steals books.", 
    featured: true,
    color: "from-gray-400 to-slate-400"
  },
  { 
    id: 14, 
    title: "The Handmaid's Tale", 
    author: "Margaret Atwood", 
    price: 16.99, 
    category: "Dystopian", 
    rating: 4.5, 
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=300&h=400&fit=crop&crop=center", 
    description: "A dystopian novel about women's rights and totalitarianism.", 
    featured: false,
    color: "from-red-400 to-pink-400"
  },
  { 
    id: 15, 
    title: "The Seven Husbands of Evelyn Hugo", 
    author: "Taylor Jenkins Reid", 
    price: 17.99, 
    category: "Romance", 
    rating: 4.8, 
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&h=400&fit=crop&crop=center", 
    description: "A captivating story of a reclusive Hollywood icon.", 
    featured: true,
    color: "from-purple-400 to-pink-400"
  }
];
export default booksData;
